### ISSUE TITLE
mimi.sleek123@gmail.com

### ISSUE THREAD

**Issue by veraahmad** [kingcamofficial/HigherPowers#10]
مرحبا انا جديدة في الموقع عندي خطا في تثبيت اللينكس بالترمكس جربت طريقتين بدون فائدة ارجو المساعدة من فريق الدعم  ارجو مراسلتي عبر بريدي الالكتروني

**Comment by kingcamofficial** [comment]
I am also new to this site as well.

**Comment by veraahmad** [comment]
هل في احد لديه خبرة في لصق لينكس في ترمكس يا جماعة نحن بامس الحاجة للمساعدة اين الخبراء في هذا المجال ؟؟

**Comment by veraahmad** [comment]
> أنا أيضًا جديد في هذا الموقع.

مرحبا هل وجدت احدا يساعدك ؟؟ انا لم اجد احدا

**Comment by kingcamofficial** [comment]
I do know some but not much email me at camandmusiccorp@gmail.com maybe we can work together on something until we find someone more experienced plus I go to full sail university and get a lot of help through them as well

**Comment by veraahmad** [comment]
Yes, with pleasure, I am glad that we can work together and help  each
other, I have books about termex and Linux, but I need help with termex,
can I send you this e-mail ?

في الاثنين، ٥ سبتمبر ٢٠٢٢ ٢:٠٠ م kingcamofficial ***@***.***>
كتب:

**Comment by kingcamofficial** [comment]
yes

**Comment by veraahmad** [comment]
؟؟؟

في السبت، ٢٤ سبتمبر ٢٠٢٢ ٢:٢٨ ص Cameron C Andrews ***@***.***>
كتب:
